// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: icare-policy-service.proto

package icare.policy.service.grpc;

public final class IcarePolicyService {
  private IcarePolicyService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_icare_policy_service_grpc_Policy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_icare_policy_service_grpc_Policy_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032icare-policy-service.proto\022\031icare.poli" +
      "cy.service.grpc\"r\n\006Policy\022\n\n\002id\030\001 \001(\005\022\024\n" +
      "\014policyHolder\030\002 \001(\t\022\013\n\003lob\030\003 \001(\t\022\016\n\006stat" +
      "us\030\004 \001(\t\022\024\n\014maturityDate\030\005 \001(\t\022\023\n\013maturi" +
      "tyAmt\030\006 \001(\t2^\n\rPolicyService\022M\n\005apply\022!." +
      "icare.policy.service.grpc.Policy\032!.icare" +
      ".policy.service.grpc.PolicyB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_icare_policy_service_grpc_Policy_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_icare_policy_service_grpc_Policy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_icare_policy_service_grpc_Policy_descriptor,
        new java.lang.String[] { "Id", "PolicyHolder", "Lob", "Status", "MaturityDate", "MaturityAmt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
