// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: icare-policy-service.proto

package icare.policy.service.grpc;

import com.google.protobuf.ByteString;

/**
 * Protobuf type {@code icare.policy.service.grpc.Policy}
 */
public final class Policy extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:icare.policy.service.grpc.Policy)
    PolicyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Policy.newBuilder() to construct.
  private Policy(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Policy() {
    policyHolder_ = "";
    lob_ = "";
    status_ = "";
    maturityDate_ = "";
    maturityAmt_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Policy();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Policy(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            policyHolder_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            lob_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            maturityDate_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            maturityAmt_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return icare.policy.service.grpc.IcarePolicyService.internal_static_icare_policy_service_grpc_Policy_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return icare.policy.service.grpc.IcarePolicyService.internal_static_icare_policy_service_grpc_Policy_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            icare.policy.service.grpc.Policy.class, icare.policy.service.grpc.Policy.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  public int getId() {
    return id_;
  }

  public static final int POLICYHOLDER_FIELD_NUMBER = 2;
  private volatile java.lang.Object policyHolder_;
  /**
   * <code>string policyHolder = 2;</code>
   * @return The policyHolder.
   */
  public java.lang.String getPolicyHolder() {
    java.lang.Object ref = policyHolder_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      policyHolder_ = s;
      return s;
    }
  }
  /**
   * <code>string policyHolder = 2;</code>
   * @return The bytes for policyHolder.
   */
  public com.google.protobuf.ByteString
      getPolicyHolderBytes() {
    java.lang.Object ref = policyHolder_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      policyHolder_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOB_FIELD_NUMBER = 3;
  private volatile java.lang.Object lob_;
  /**
   * <code>string lob = 3;</code>
   * @return The lob.
   */
  public java.lang.String getLob() {
    java.lang.Object ref = lob_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lob_ = s;
      return s;
    }
  }
  /**
   * <code>string lob = 3;</code>
   * @return The bytes for lob.
   */
  public com.google.protobuf.ByteString
      getLobBytes() {
    java.lang.Object ref = lob_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lob_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private volatile java.lang.Object status_;
  /**
   * <code>string status = 4;</code>
   * @return The status.
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 4;</code>
   * @return The bytes for status.
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MATURITYDATE_FIELD_NUMBER = 5;
  private volatile java.lang.Object maturityDate_;
  /**
   * <code>string maturityDate = 5;</code>
   * @return The maturityDate.
   */
  public java.lang.String getMaturityDate() {
    java.lang.Object ref = maturityDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      maturityDate_ = s;
      return s;
    }
  }
  /**
   * <code>string maturityDate = 5;</code>
   * @return The bytes for maturityDate.
   */
  public com.google.protobuf.ByteString
      getMaturityDateBytes() {
    java.lang.Object ref = maturityDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      maturityDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MATURITYAMT_FIELD_NUMBER = 6;
  private volatile java.lang.Object maturityAmt_;
  /**
   * <code>string maturityAmt = 6;</code>
   * @return The maturityAmt.
   */
  public java.lang.String getMaturityAmt() {
    java.lang.Object ref = maturityAmt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      maturityAmt_ = s;
      return s;
    }
  }
  /**
   * <code>string maturityAmt = 6;</code>
   * @return The bytes for maturityAmt.
   */
  public com.google.protobuf.ByteString
      getMaturityAmtBytes() {
    java.lang.Object ref = maturityAmt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      maturityAmt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(policyHolder_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, policyHolder_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lob_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lob_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(maturityDate_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, maturityDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(maturityAmt_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, maturityAmt_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(policyHolder_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, policyHolder_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lob_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lob_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(maturityDate_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, maturityDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(maturityAmt_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, maturityAmt_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof icare.policy.service.grpc.Policy)) {
      return super.equals(obj);
    }
    icare.policy.service.grpc.Policy other = (icare.policy.service.grpc.Policy) obj;

    if (getId()
        != other.getId()) return false;
    if (!getPolicyHolder()
        .equals(other.getPolicyHolder())) return false;
    if (!getLob()
        .equals(other.getLob())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getMaturityDate()
        .equals(other.getMaturityDate())) return false;
    if (!getMaturityAmt()
        .equals(other.getMaturityAmt())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + POLICYHOLDER_FIELD_NUMBER;
    hash = (53 * hash) + getPolicyHolder().hashCode();
    hash = (37 * hash) + LOB_FIELD_NUMBER;
    hash = (53 * hash) + getLob().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + MATURITYDATE_FIELD_NUMBER;
    hash = (53 * hash) + getMaturityDate().hashCode();
    hash = (37 * hash) + MATURITYAMT_FIELD_NUMBER;
    hash = (53 * hash) + getMaturityAmt().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static icare.policy.service.grpc.Policy parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static icare.policy.service.grpc.Policy parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static icare.policy.service.grpc.Policy parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static icare.policy.service.grpc.Policy parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static icare.policy.service.grpc.Policy parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static icare.policy.service.grpc.Policy parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static icare.policy.service.grpc.Policy parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static icare.policy.service.grpc.Policy parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static icare.policy.service.grpc.Policy parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static icare.policy.service.grpc.Policy parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static icare.policy.service.grpc.Policy parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static icare.policy.service.grpc.Policy parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(icare.policy.service.grpc.Policy prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code icare.policy.service.grpc.Policy}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:icare.policy.service.grpc.Policy)
      icare.policy.service.grpc.PolicyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return icare.policy.service.grpc.IcarePolicyService.internal_static_icare_policy_service_grpc_Policy_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return icare.policy.service.grpc.IcarePolicyService.internal_static_icare_policy_service_grpc_Policy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              icare.policy.service.grpc.Policy.class, icare.policy.service.grpc.Policy.Builder.class);
    }

    // Construct using icare.policy.service.grpc.Policy.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      policyHolder_ = "";

      lob_ = "";

      status_ = "";

      maturityDate_ = "";

      maturityAmt_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return icare.policy.service.grpc.IcarePolicyService.internal_static_icare_policy_service_grpc_Policy_descriptor;
    }

    public icare.policy.service.grpc.Policy getDefaultInstanceForType() {
      return icare.policy.service.grpc.Policy.getDefaultInstance();
    }

    public icare.policy.service.grpc.Policy build() {
      icare.policy.service.grpc.Policy result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public icare.policy.service.grpc.Policy buildPartial() {
      icare.policy.service.grpc.Policy result = new icare.policy.service.grpc.Policy(this);
      result.id_ = id_;
      result.policyHolder_ = policyHolder_;
      result.lob_ = lob_;
      result.status_ = status_;
      result.maturityDate_ = maturityDate_;
      result.maturityAmt_ = maturityAmt_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof icare.policy.service.grpc.Policy) {
        return mergeFrom((icare.policy.service.grpc.Policy)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(icare.policy.service.grpc.Policy other) {
      if (other == icare.policy.service.grpc.Policy.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getPolicyHolder().isEmpty()) {
        policyHolder_ = other.policyHolder_;
        onChanged();
      }
      if (!other.getLob().isEmpty()) {
        lob_ = other.lob_;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (!other.getMaturityDate().isEmpty()) {
        maturityDate_ = other.maturityDate_;
        onChanged();
      }
      if (!other.getMaturityAmt().isEmpty()) {
        maturityAmt_ = other.maturityAmt_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      icare.policy.service.grpc.Policy parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (icare.policy.service.grpc.Policy) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object policyHolder_ = "";
    /**
     * <code>string policyHolder = 2;</code>
     * @return The policyHolder.
     */
    public java.lang.String getPolicyHolder() {
      java.lang.Object ref = policyHolder_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        policyHolder_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string policyHolder = 2;</code>
     * @return The bytes for policyHolder.
     */
    public com.google.protobuf.ByteString
        getPolicyHolderBytes() {
      java.lang.Object ref = policyHolder_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        policyHolder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string policyHolder = 2;</code>
     * @param value The policyHolder to set.
     * @return This builder for chaining.
     */
    public Builder setPolicyHolder(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      policyHolder_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string policyHolder = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPolicyHolder() {
      
      policyHolder_ = getDefaultInstance().getPolicyHolder();
      onChanged();
      return this;
    }
    /**
     * <code>string policyHolder = 2;</code>
     * @param value The bytes for policyHolder to set.
     * @return This builder for chaining.
     */
    public Builder setPolicyHolderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      policyHolder_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lob_ = "";
    /**
     * <code>string lob = 3;</code>
     * @return The lob.
     */
    public java.lang.String getLob() {
      java.lang.Object ref = lob_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lob_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lob = 3;</code>
     * @return The bytes for lob.
     */
    public com.google.protobuf.ByteString
        getLobBytes() {
      java.lang.Object ref = lob_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lob_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lob = 3;</code>
     * @param value The lob to set.
     * @return This builder for chaining.
     */
    public Builder setLob(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lob_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lob = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLob() {
      
      lob_ = getDefaultInstance().getLob();
      onChanged();
      return this;
    }
    /**
     * <code>string lob = 3;</code>
     * @param value The bytes for lob to set.
     * @return This builder for chaining.
     */
    public Builder setLobBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lob_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 4;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 4;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 4;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string status = 4;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object maturityDate_ = "";
    /**
     * <code>string maturityDate = 5;</code>
     * @return The maturityDate.
     */
    public java.lang.String getMaturityDate() {
      java.lang.Object ref = maturityDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        maturityDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string maturityDate = 5;</code>
     * @return The bytes for maturityDate.
     */
    public com.google.protobuf.ByteString
        getMaturityDateBytes() {
      java.lang.Object ref = maturityDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        maturityDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string maturityDate = 5;</code>
     * @param value The maturityDate to set.
     * @return This builder for chaining.
     */
    public Builder setMaturityDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      maturityDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string maturityDate = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaturityDate() {
      
      maturityDate_ = getDefaultInstance().getMaturityDate();
      onChanged();
      return this;
    }
    /**
     * <code>string maturityDate = 5;</code>
     * @param value The bytes for maturityDate to set.
     * @return This builder for chaining.
     */
    public Builder setMaturityDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      maturityDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object maturityAmt_ = "";
    /**
     * <code>string maturityAmt = 6;</code>
     * @return The maturityAmt.
     */
    public java.lang.String getMaturityAmt() {
      java.lang.Object ref = maturityAmt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        maturityAmt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string maturityAmt = 6;</code>
     * @return The bytes for maturityAmt.
     */
    public com.google.protobuf.ByteString
        getMaturityAmtBytes() {
      java.lang.Object ref = maturityAmt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        maturityAmt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string maturityAmt = 6;</code>
     * @param value The maturityAmt to set.
     * @return This builder for chaining.
     */
    public Builder setMaturityAmt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      maturityAmt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string maturityAmt = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaturityAmt() {
      
      maturityAmt_ = getDefaultInstance().getMaturityAmt();
      onChanged();
      return this;
    }
    /**
     * <code>string maturityAmt = 6;</code>
     * @param value The bytes for maturityAmt to set.
     * @return This builder for chaining.
     */
    public Builder setMaturityAmtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      maturityAmt_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:icare.policy.service.grpc.Policy)
  }

  // @@protoc_insertion_point(class_scope:icare.policy.service.grpc.Policy)
  private static final icare.policy.service.grpc.Policy DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new icare.policy.service.grpc.Policy();
  }

  public static icare.policy.service.grpc.Policy getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Policy>
      PARSER = new com.google.protobuf.AbstractParser<Policy>() {
    public Policy parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Policy(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Policy> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Policy> getParserForType() {
    return PARSER;
  }

  public icare.policy.service.grpc.Policy getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}

