// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: icare-policy-service.proto

package icare.policy.service.grpc;

public interface PolicyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:icare.policy.service.grpc.Policy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string policyHolder = 2;</code>
   * @return The policyHolder.
   */
  java.lang.String getPolicyHolder();
  /**
   * <code>string policyHolder = 2;</code>
   * @return The bytes for policyHolder.
   */
  com.google.protobuf.ByteString
      getPolicyHolderBytes();

  /**
   * <code>string lob = 3;</code>
   * @return The lob.
   */
  java.lang.String getLob();
  /**
   * <code>string lob = 3;</code>
   * @return The bytes for lob.
   */
  com.google.protobuf.ByteString
      getLobBytes();

  /**
   * <code>string status = 4;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 4;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string maturityDate = 5;</code>
   * @return The maturityDate.
   */
  java.lang.String getMaturityDate();
  /**
   * <code>string maturityDate = 5;</code>
   * @return The bytes for maturityDate.
   */
  com.google.protobuf.ByteString
      getMaturityDateBytes();

  /**
   * <code>string maturityAmt = 6;</code>
   * @return The maturityAmt.
   */
  java.lang.String getMaturityAmt();
  /**
   * <code>string maturityAmt = 6;</code>
   * @return The bytes for maturityAmt.
   */
  com.google.protobuf.ByteString
      getMaturityAmtBytes();
}
